import "./globals.css";
import Providers from "./providers";
import ThemeSwitcher from "./components/ThemeSwitcher";
import Header from "./components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main className="px-6 py-10">
            <div className="flex flex-col gap-8 max-w-[1350px] mx-auto">
              {children}
            </div>
          </main>

        </Providers>
      </body>
    </html>
  );
}